# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bd < Formula
  desc "AI-supervised issue tracker for coding workflows"
  homepage "https://github.com/steveyegge/beads"
  version "0.21.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steveyegge/beads/releases/download/v0.21.2/beads_0.21.2_darwin_amd64.tar.gz"
      sha256 "c877171d54fa0270601cd48a817f8acdc3b8b091afdc5997b3aa0aa61e82b1df"

      def install
        bin.install "bd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steveyegge/beads/releases/download/v0.21.2/beads_0.21.2_darwin_arm64.tar.gz"
      sha256 "ef06c2f8dcd72424563ab6661bba01d0493f87a74f616303b44064609d4b28ff"

      def install
        bin.install "bd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveyegge/beads/releases/download/v0.21.2/beads_0.21.2_linux_amd64.tar.gz"
      sha256 "1ede94b38f6f3ec5bc50b507c5491a9a508c0c88ca3299c2daed964a4816da1b"
      def install
        bin.install "bd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/steveyegge/beads/releases/download/v0.21.2/beads_0.21.2_linux_arm64.tar.gz"
      sha256 "4eaee34c8adb38707f9b82a4b52530d17582fff3b9892377afa448272e5a8d73"
      def install
        bin.install "bd"
      end
    end
  end

  test do
    system "#{bin}/bd", "version"
  end
end
